name: flutter_e_commerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  firebase_storage: ^10.2.9
  google_sign_in: ^5.2.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flow_builder: ^0.0.4
  formz: ^0.4.0
  meta: ^1.7.0
  google_fonts: ^2.3.1
  very_good_analysis: ^2.4.0
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^1.0.3
  cloud_firestore: ^3.1.10
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPro/SF-Pro-Display-Ultralight.otf
          style: normal
          weight: 100
        - asset: assets/fonts/SFPro/SF-Pro-Display-UltralightItalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/SFPro/SF-Pro-Display-Thin.otf
          style: normal
          weight: 200
        - asset: assets/fonts/SFPro/SF-Pro-Display-ThinItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/SFPro/SF-Pro-Display-Light.otf
          style: normal
          weight: 300
        - asset: assets/fonts/SFPro/SF-Pro-Display-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/SFPro/SF-Pro-Display-Regular.otf
          style: normal
          weight: 400
        - asset: assets/fonts/SFPro/SF-Pro-Display-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/SFPro/SF-Pro-Display-Medium.otf
          style: normal
          weight: 500
        - asset: assets/fonts/SFPro/SF-Pro-Display-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/SFPro/SF-Pro-Display-Semibold.otf
          style: normal
          weight: 600
        - asset: assets/fonts/SFPro/SF-Pro-Display-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/SFPro/SF-Pro-Display-Bold.otf
          style: normal
          weight: 700
        - asset: assets/fonts/SFPro/SF-Pro-Display-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/SFPro/SF-Pro-Display-Heavy.otf
          style: normal
          weight: 800
        - asset: assets/fonts/SFPro/SF-Pro-Display-HeavyItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/SFPro/SF-Pro-Display-Black.otf
          style: normal
          weight: 900
        - asset: assets/fonts/SFPro/SF-Pro-Display-BlackItalic.otf
          style: italic
          weight: 900
      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

