name: flutter_e_commerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  firebase_storage: ^10.2.9
  google_sign_in: ^5.2.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flow_builder: ^0.0.4
  formz: ^0.4.0
  meta: ^1.7.0
  google_fonts: ^2.3.1
  very_good_analysis: ^2.4.0
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^1.0.3
  cloud_firestore: ^3.1.10
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

